CREATE TABLE IF NOT EXISTS users
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                 VARCHAR(255) NOT NULL UNIQUE,
    password                 VARCHAR(255) NOT NULL,
    name                     VARCHAR(20)  NOT NULL,
    code                     VARCHAR(20),
    phone_number             VARCHAR(255),
    department               VARCHAR(255),
    last_password_change_date TIMESTAMP,
    created_at               TIMESTAMP    NOT NULL,
    updated_at               TIMESTAMP    NOT NULL,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(100),
    auth        VARCHAR(255),
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL REFERENCES users (id),
    role_id    BIGINT    NOT NULL REFERENCES roles (id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS permission
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS role_permission
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT REFERENCES roles (id),
    permission_id BIGINT REFERENCES permission (id)
);

CREATE TABLE IF NOT EXISTS user_resource_permissions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL,
    resource_type VARCHAR(255) NOT NULL,
    resource_id   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS domain_permission
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_name VARCHAR(255) NOT NULL,
    level         VARCHAR(255) NOT NULL,
    permission_id BIGINT REFERENCES permission (id),
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT uq_domain_permission_resource UNIQUE (permission_id, resource_name)
);

CREATE TABLE IF NOT EXISTS resource_permission
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_name VARCHAR(255) NOT NULL,
    resource_id   VARCHAR(255) NOT NULL,
    level         VARCHAR(255) NOT NULL,
    permission_id BIGINT REFERENCES permission (id),
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT uq_resource_permission_resource UNIQUE (permission_id, resource_name, resource_id)
);
