server:
  servlet:
    context-path: /api

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 1000
  application:
    name: yongin-api
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/safers
    username: ${DB_USERNAME:pluxity}
    password: ${DB_PASSWORD:pluxity0304}

domain:
  url: ${API_URL:}

