-- 통합 디바이스 마스터 (gas / band / sos 가 한 테이블, type 디스크리미네이터 + metadata jsonb)
-- 식별: surrogate Long PK + 비즈니스 키 (device_id, site_id) 복합 unique
--   같은 device_id 라도 site 가 다르면 별개 row 로 등록 가능
CREATE TABLE IF NOT EXISTS device
(
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id     VARCHAR(64)  NOT NULL,
    type          VARCHAR(16)  NOT NULL,
    site_id       BIGINT       NOT NULL,
    name          VARCHAR(128),
    status        VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    last_seen_at  TIMESTAMP,
    metadata      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT uk_device_id_site UNIQUE (device_id, site_id)
);

CREATE INDEX IF NOT EXISTS idx_device_site_status ON device (site_id, status);
CREATE INDEX IF NOT EXISTS idx_device_type        ON device (type);
CREATE INDEX IF NOT EXISTS idx_device_metadata    ON device USING GIN (metadata jsonb_path_ops);
