CREATE TABLE IF NOT EXISTS sites
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    construction_start_date DATE,
    construction_end_date   DATE,
    description             VARCHAR(255),
    region                  VARCHAR(255),
    address                 VARCHAR(255),
    thumbnail_image_id      BIGINT,
    location                geometry(Polygon, 4326),
    base_url                VARCHAR(255),
    nx                      INTEGER      NOT NULL,
    ny                      INTEGER      NOT NULL,
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cctv_stream
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id     BIGINT       NOT NULL REFERENCES sites (id),
    stream_name VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    lon         DOUBLE PRECISION,
    lat         DOUBLE PRECISION,
    alt         DOUBLE PRECISION,
    nvr_id      VARCHAR(255),
    channel     INTEGER,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS events
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id        VARCHAR(255) NOT NULL,
    event_timestamp TIMESTAMP    NOT NULL,
    category        VARCHAR(255) NOT NULL,
    type            VARCHAR(255) NOT NULL,
    track_id        BIGINT       NOT NULL,
    name            VARCHAR(255) NOT NULL,
    bbox            VARCHAR(255),
    center_x        DOUBLE PRECISION,
    center_y        DOUBLE PRECISION,
    confidence      DOUBLE PRECISION,
    path            VARCHAR(255),
    snapshot_file_id BIGINT,
    video_file_id   BIGINT,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS weathers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    BIGINT       NOT NULL REFERENCES sites (id),
    base_date  VARCHAR(255) NOT NULL,
    base_time  VARCHAR(255) NOT NULL,
    category   VARCHAR(255) NOT NULL,
    fcst_date  VARCHAR(255) NOT NULL,
    fcst_time  VARCHAR(255) NOT NULL,
    fcst_value VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT uk_weather_fcst UNIQUE (fcst_date, fcst_time, category, site_id)
);

CREATE TABLE IF NOT EXISTS configurations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   VARCHAR(255) NOT NULL UNIQUE,
    config_value VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255)
);
