CREATE TABLE IF NOT EXISTS files
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path          VARCHAR(255) NOT NULL UNIQUE,
    original_file_name VARCHAR(255) NOT NULL,
    content_type       VARCHAR(255) NOT NULL,
    file_status        VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP    NOT NULL,
    updated_at         TIMESTAMP    NOT NULL,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS zip_content_entries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id      BIGINT       NOT NULL REFERENCES files (id),
    name         VARCHAR(255) NOT NULL,
    is_directory BOOLEAN      NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255)
);
