CREATE TABLE IF NOT EXISTS announcement
(
    id         BIGINT       NOT NULL PRIMARY KEY,
    content    TEXT,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cctv_stream
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name VARCHAR(255) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    lon         DOUBLE PRECISION,
    lat         DOUBLE PRECISION,
    alt         DOUBLE PRECISION,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cctv_bookmark
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_name   VARCHAR(255) NOT NULL,
    display_order INTEGER      NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    CONSTRAINT uk_cctv_bookmark_stream_name UNIQUE (stream_name)
);

CREATE TABLE IF NOT EXISTS construction_section
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS goal
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input_date                   DATE      NOT NULL,
    construction_section_id      BIGINT    NOT NULL REFERENCES construction_section (id),
    progress_rate                REAL,
    construction_rate            REAL,
    total_quantity               INTEGER,
    cumulative_quantity          INTEGER,
    previous_cumulative_quantity INTEGER,
    target_quantity              INTEGER,
    work_quantity                INTEGER,
    start_date                   DATE,
    completion_date              DATE,
    planned_work_days            INTEGER,
    delay_days                   INTEGER,
    is_active                    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at                   TIMESTAMP NOT NULL,
    updated_at                   TIMESTAMP NOT NULL,
    created_by                   VARCHAR(255),
    updated_by                   VARCHAR(255),
    CONSTRAINT uk_goal_input_date_construction_section UNIQUE (input_date, construction_section_id)
);

CREATE TABLE IF NOT EXISTS key_management
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             VARCHAR(255) NOT NULL,
    title            VARCHAR(255) NOT NULL,
    method_feature   TEXT,
    method_content   TEXT,
    method_direction TEXT,
    display_order    INTEGER,
    file_id          BIGINT,
    selected         BOOLEAN,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS notice
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255)  NOT NULL,
    content    VARCHAR(1000),
    is_visible BOOLEAN       NOT NULL DEFAULT FALSE,
    is_always  BOOLEAN       NOT NULL DEFAULT FALSE,
    start_date DATE,
    end_date   DATE,
    created_at TIMESTAMP     NOT NULL,
    updated_at TIMESTAMP     NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS observation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE         NOT NULL,
    description    VARCHAR(255),
    file_id        BIGINT       NOT NULL,
    root_file_name VARCHAR(255) NOT NULL,
    directory_path VARCHAR(255),
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS work_type
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS process_status
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date    DATE      NOT NULL,
    work_type_id BIGINT    NOT NULL REFERENCES work_type (id),
    planned_rate INTEGER,
    actual_rate  INTEGER,
    is_active    BOOLEAN   NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP NOT NULL,
    updated_at   TIMESTAMP NOT NULL,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    CONSTRAINT uk_process_status_work_date_work_type UNIQUE (work_date, work_type_id)
);

CREATE TABLE IF NOT EXISTS process_status_image
(
    id         BIGINT    NOT NULL PRIMARY KEY,
    file_id    BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS safety_equipments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    quantity   INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS system_settings
(
    id                       BIGINT    NOT NULL PRIMARY KEY,
    rolling_interval_seconds INTEGER   NOT NULL,
    bim_thumbnail_file_id    BIGINT,
    aerial_view_file_id      BIGINT,
    created_at               TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP NOT NULL,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS attendance
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_date  DATE         NOT NULL,
    device_name      VARCHAR(255) NOT NULL,
    attendance_count INTEGER      NOT NULL,
    work_content     VARCHAR(255),
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    CONSTRAINT uk_attendance_date_device_name UNIQUE (attendance_date, device_name)
);

CREATE TABLE IF NOT EXISTS weather
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measured_at    VARCHAR(255)     NOT NULL,
    temperature    DOUBLE PRECISION NOT NULL,
    humidity       DOUBLE PRECISION NOT NULL,
    wind_speed     DOUBLE PRECISION NOT NULL,
    wind_direction VARCHAR(255)     NOT NULL,
    rainfall       INTEGER          NOT NULL,
    pm10           INTEGER          NOT NULL,
    pm25           INTEGER          NOT NULL,
    pm10_status    VARCHAR(255)     NOT NULL,
    pm25_status    VARCHAR(255)     NOT NULL,
    noise          DOUBLE PRECISION NOT NULL,
    created_at     TIMESTAMP        NOT NULL,
    updated_at     TIMESTAMP        NOT NULL,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255)
);
